'harper-medusa-commerce':
  package: .
  files: '**'

components:
  '@harperdb/nextjs':
    package: '@harperdb/nextjs'
    port: 9926
    prebuilt: true

graphqlSchema:
  files: 'schema.graphql'    # This tells HarperDB to load your schema

jsResource:
  files: 'resources.js'
  path: '/api'
